---
name: Release
on:
  workflow_dispatch:
jobs:
  tag:
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Config
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Release Tag
        id: release_tag
        env:
          RELEASE_NUMBER: $(date +'%Y.%m.%d.%H%M')
        run: |
          git tag ${{env.RELEASE_NUMBER}} -m "Create ${{env.RELEASE_NUMBER}} Release"
          echo "::set-output name=RELEASE_NUMBER::${{env.RELEASE_NUMBER}}"
          git push origin --tags
          git push -u origin HEAD:release/${{env.RELEASE_NUMBER}}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{steps.release_tag.outputs.RELEASE_NUMBER}}
          tag_name: ${{steps.release_tag.outputs.RELEASE_NUMBER}}
